### ISSUE TITLE
运行项目报错

### ISSUE THREAD

**Issue by qq843212285** [donghaikun/OnceLove#5]
![1545790561 1](https://user-images.githubusercontent.com/24998114/50429136-522aed00-08f7-11e9-890f-11efa02fe0b3.png)
这个是什么问题

**Comment by donghaikun** [comment]
mainInfo这个是从接口请求来的 你看下onload时的请求是否有返回
另：默认程序用的是我提供的接口 自行搭建需要替换app.js中的server url
